=== JosebaFernandez/proyectoESports/LDM/FASE CUATRO/Clasificacion XML/clasificaciones_dtd_v2.dtd
<!ELEMENT competiciones (competicion+)>
<!ELEMENT competicion (nombre_comp, juego, equipos, fecha)>
<!ATTLIST competicion id ID #REQUIRED>
<!ELEMENT nombre_comp (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

<!ELEMENT juego (nombre_juego)>
<!ATTLIST juego id ID #REQUIRED>
<!ELEMENT nombre_juego (#PCDATA)>

<!ELEMENT equipos (equipo+)>
<!ELEMENT equipo (nombre_eq, puntos_totales)>
<!ATTLIST equipo id ID #REQUIRED>
<!ELEMENT nombre_eq (#PCDATA)>
<!ELEMENT puntos_totales (#PCDATA)>

=== JosebaFernandez/proyectoESports/LDM/FASE CUATRO/Clasificacion XML/clasificaciones_xml_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE competiciones SYSTEM "clasificaciones_dtd_v2.dtd">
<competiciones>
    <competicion id="comp1">
        <nombre_comp>Campeonato Internacional</nombre_comp>
        <juego id="jue1">
            <nombre_juego>League of Legends</nombre_juego>
        </juego>
        <equipos>
            <equipo id="eq1">
                <nombre_eq>Equipo Alpha</nombre_eq>
                <puntos_totales>30</puntos_totales>
            </equipo>
            <equipo id="eq2">
                <nombre_eq>Equipo Beta</nombre_eq>
                <puntos_totales>28</puntos_totales>
            </equipo>
            <equipo id="eq3">
                <nombre_eq>Equipo Gamma</nombre_eq>
                <puntos_totales>25</puntos_totales>
            </equipo>
        </equipos>
        <fecha>2024-05-14</fecha>
    </competicion>
    <competicion id="comp2">
        <nombre_comp>Torneo Nacional</nombre_comp>
        <juego id="jue2">
            <nombre_juego>Counter-Strike: Global Offensive</nombre_juego>
        </juego>
        <equipos>
            <equipo id="eq4">
                <nombre_eq>Equipo Delta</nombre_eq>
                <puntos_totales>35</puntos_totales>
            </equipo>
            <equipo id="eq5">
                <nombre_eq>Equipo Epsilon</nombre_eq>
                <puntos_totales>32</puntos_totales>
            </equipo>
            <equipo id="eq6">
                <nombre_eq>Equipo Zeta</nombre_eq>
                <puntos_totales>29</puntos_totales>
            </equipo>
        </equipos>
        <fecha>2024-06-20</fecha>
    </competicion>
</competiciones>
