=== JosebaFernandez/proyectoESports/LDM/FASE TRES/Jornadas XML/XSD/Jornadas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definición del elemento raíz -->
    <xs:element name="competiciones" type="competicionesType"/>

    <!-- Definición del tipo complexType para competiciones -->
    <xs:complexType name="competicionesType">
        <xs:sequence>
            <xs:element name="competicion" type="competicionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definición del tipo complexType para competicion -->
    <xs:complexType name="competicionType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="juego" type="xs:string"/>
            <xs:element name="jornadas" type="jornadasType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Definición del tipo complexType para jornadas -->
    <xs:complexType name="jornadasType">
        <xs:sequence>
            <xs:element name="jornada" type="jornadaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definición del tipo complexType para jornada -->
    <xs:complexType name="jornadaType">
        <xs:sequence>
            <xs:element name="n_jornada" type="xs:integer"/>
            <xs:element name="fecha_jornada" type="xs:date"/>
            <xs:element name="enfrentamientos" type="enfrentamientosType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Definición del tipo complexType para enfrentamientos -->
    <xs:complexType name="enfrentamientosType">
        <xs:sequence>
            <xs:element name="enfrentamiento" type="enfrentamientoType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definición del tipo complexType para enfrentamiento -->
    <xs:complexType name="enfrentamientoType">
        <xs:sequence>
            <xs:element name="hora" type="xs:string"/>
            <xs:element name="equipo_local" type="xs:string"/>
            <xs:element name="equipo_visitante" type="xs:string"/>
            <xs:element name="resultado" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== JosebaFernandez/proyectoESports/LDM/FASE CUATRO/Jornadas XML/XSD/JornadasXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<competiciones 
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"       
    xs:noNamespaceSchemaLocation="Jornadas.xsd">
    <competicion id="c100">
        <nombre>LaLiga</nombre>
        <juego>Futbol</juego>
        <jornadas>
            <jornada id="j010">
                <n_jornada>1</n_jornada>
                <fecha_jornada>2024-01-10</fecha_jornada>
                <enfrentamientos>
                    <enfrentamiento id="e011">
                        <hora>15:30</hora>
                        <equipo_local>Team Alpha</equipo_local>
                        <equipo_visitante>Team Beta</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                    <enfrentamiento id="e012">
                        <hora>16:30</hora>
                        <equipo_local>Team Bar√ßa</equipo_local>
                        <equipo_visitante>Team Madrid</equipo_visitante>
                        <resultado>Gana local</resultado>
                    </enfrentamiento>
                </enfrentamientos>
            </jornada>
            <jornada id="j020">
                <n_jornada>2</n_jornada>
                <fecha_jornada>2024-01-17</fecha_jornada>
                <enfrentamientos>
                    <enfrentamiento id="e021">
                        <hora>15:30</hora>
                        <equipo_local>Team Hola</equipo_local>
                        <equipo_visitante>Team Adios</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                    <enfrentamiento id="e022">
                        <hora>16:30</hora>
                        <equipo_local>Team Rojo</equipo_local>
                        <equipo_visitante>Team Azul</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                </enfrentamientos>
            </jornada>
        </jornadas>
    </competicion>
    <competicion id="c200">
        <nombre>LigaBasket</nombre>
        <juego>Baloncesto</juego>
        <jornadas>
            <jornada id="j110">
                <n_jornada>1</n_jornada>
                <fecha_jornada>2024-01-10</fecha_jornada>
                <enfrentamientos>
                    <enfrentamiento id="e031">
                        <hora>17:30</hora>
                        <equipo_local>Team Blanco</equipo_local>
                        <equipo_visitante>Team Negro</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                    <enfrentamiento id="e032">
                        <hora>18:30</hora>
                        <equipo_local>Team Marron</equipo_local>
                        <equipo_visitante>Team Alaves</equipo_visitante>
                        <resultado>Gana local</resultado>
                    </enfrentamiento>
                </enfrentamientos>
            </jornada>
            <jornada id="j120">
                <n_jornada>2</n_jornada>
                <fecha_jornada>2024-01-17</fecha_jornada>
                <enfrentamientos>
                    <enfrentamiento id="e041">
                        <hora>19:30</hora>
                        <equipo_local>Team Amarillo</equipo_local>
                        <equipo_visitante>Team Verde</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                    <enfrentamiento id="e042">
                        <hora>20:30</hora>
                        <equipo_local>Team Arriba</equipo_local>
                        <equipo_visitante>Team Abajo</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                </enfrentamientos>
            </jornada>
        </jornadas>
    </competicion>
</competiciones>
