=== JosebaFernandez/proyectoESports/LDM/FASE CUATRO/Ultima Jornada XML/DTD/Ultima_Jornada.dtd
<!ELEMENT competiciones (competicion+)>
    <!ELEMENT competicion (nombre, juego, jornada+)>
    <!ATTLIST competicion id CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT juego (#PCDATA)>
    <!ELEMENT jornada (n_jornada, fecha_jornada, enfrentamientos)>
    <!ATTLIST jornada id CDATA #REQUIRED>
    <!ELEMENT n_jornada (#PCDATA)>
    <!ELEMENT fecha_jornada (#PCDATA)>
    <!ELEMENT enfrentamientos (enfrentamiento+)>
    <!ELEMENT enfrentamiento (hora, equipo_local, equipo_visitante, resultado)>
    <!ATTLIST enfrentamiento id CDATA #REQUIRED>
    <!ELEMENT hora (#PCDATA)>
    <!ELEMENT equipo_local (#PCDATA)>
    <!ELEMENT equipo_visitante (#PCDATA)>
    <!ELEMENT resultado (#PCDATA)>

=== JosebaFernandez/proyectoESports/LDM/FASE CUATRO/Ultima Jornada XML/DTD/Ultima_JornadaDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE competiciones SYSTEM "Ultima_jornada.dtd">

<competiciones >
    <competicion id="c100">
        <nombre>LaLiga</nombre>
        <juego>Futbol</juego>
        <jornada id="j010">
                <n_jornada>1</n_jornada>
                <fecha_jornada>2024-01-10</fecha_jornada>
                <enfrentamientos>
                    <enfrentamiento id="e011">
                        <hora>15:30</hora>
                        <equipo_local>Team Alpha</equipo_local>
                        <equipo_visitante>Team Beta</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                    <enfrentamiento id="e012">
                        <hora>16:30</hora>
                        <equipo_local>Team Bar√ßa</equipo_local>
                        <equipo_visitante>Team Madrid</equipo_visitante>
                        <resultado>Gana local</resultado>
                    </enfrentamiento>
                </enfrentamientos>
        </jornada>
    </competicion>
    <competicion id="c200">
        <nombre>LigaBasket</nombre>
        <juego>Baloncesto</juego>
        <jornada id="j110">
                <n_jornada>1</n_jornada>
                <fecha_jornada>2024-01-10</fecha_jornada>
                <enfrentamientos>
                    <enfrentamiento id="e031">
                        <hora>17:30</hora>
                        <equipo_local>Team Blanco</equipo_local>
                        <equipo_visitante>Team Negro</equipo_visitante>
                        <resultado>Gana visitante</resultado>
                    </enfrentamiento>
                    <enfrentamiento id="e032">
                        <hora>18:30</hora>
                        <equipo_local>Team Marron</equipo_local>
                        <equipo_visitante>Team Alaves</equipo_visitante>
                        <resultado>Gana local</resultado>
                    </enfrentamiento>
                </enfrentamientos>
        </jornada>
    </competicion>
</competiciones>
